name: ansiCodec
description: A starting point for Dart libraries or applications.
# version: 0.1.0
# homepage: https://www.example.com
# author: gordianknot <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  hex: ^0.1.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
